services:
  yaris-agent:
    build: .
    container_name: yaris-agent
    restart: always
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./docs:/app/docs
